version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
    env_file:
      - ./server/.env
    # environment: This section can be used if .env file are not availble for development
      # - MONGODB_URI=mongodb://root:root@mongo:27017/
      # - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
  mongo:
    container_name: "mongo_service"
    image: mongo:5.0.8-focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
